use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;
use serde_json::Value;
use tokio::sync::Mutex as AMutex;
use tokio::fs;

use crate::at_commands::at_commands::AtCommandsContext;
use crate::tools::tools_description::{Tool, ToolDesc, ToolParam, ToolSource, ToolSourceType};
use crate::call_validation::{ChatMessage, ChatContent, ContextEnum};

use super::config::ESP32Config;
use super::esp32_config::{ESP32ConfigTool, PartitionConfigRequest};
use super::output_protocol::ToolOutput;
use super::idf_command::{IdfCommand, infer_project_path, get_project_name};
use super::global_state::{get_config, get_state, generate_suggested_actions, SuggestionContext};

pub struct ESP32Build {
    pub config_path: String,
}

#[async_trait]
impl Tool for ESP32Build {
    fn as_any(&self) -> &dyn std::any::Any { self }

    fn tool_description(&self) -> ToolDesc {
        ToolDesc {
            name: "esp32_build".to_string(),
            display_name: "ESP32 Build".to_string(),
            source: ToolSource {
                source_type: ToolSourceType::Builtin,
                config_path: self.config_path.clone(),
            },
            agentic: true,
            experimental: false,
            description: "Build ESP32 projects. Operations: build (compile project), clean (clean build), menuconfig (configure via menuconfig), reconfigure (regenerate config). IMPORTANT: Never open or edit the full autogenerated sdkconfig. Make changes only via sdkconfig.defaults (or sdkconfig.defaults.*). If verification is required, extract only specific CONFIG_ entries from sdkconfig (e.g., via grep), never the whole file.".to_string(),
            parameters: vec![
                ToolParam {
                    name: "operation".to_string(),
                    param_type: "string".to_string(),
                    description: "Operation: 'build' (compile), 'clean' (clean build), 'menuconfig' (open config menu), 'reconfigure' (propagate sdkconfig.defaults to autogenerated sdkconfig - run this after modifying sdkconfig.defaults)".to_string(),
                },
                ToolParam {
                    name: "project_path".to_string(),
                    param_type: "string".to_string(),
                    description: "Path to ESP32 project (default: current workspace)".to_string(),
                },
                ToolParam {
                    name: "target".to_string(),
                    param_type: "string".to_string(),
                    description: "Target chip (overrides project default)".to_string(),
                },
            ],
            parameters_required: vec!["operation".to_string()],
        }
    }

    async fn tool_execute(
        &mut self,
        ccx: Arc<AMutex<AtCommandsContext>>,
        tool_call_id: &String,
        args: &HashMap<String, Value>,
    ) -> Result<(bool, Vec<ContextEnum>), String> {
        let operation = args.get("operation")
            .and_then(|v| v.as_str())
            .ok_or("Missing required parameter: operation")?;

        let chat_id = ccx.lock().await.chat_id.clone();
        let invoked_at = std::time::SystemTime::now();
        crate::progressbar::record_tool_start(
            &chat_id,
            tool_call_id,
            "esp32_build",
            operation,
            args.clone(),
        ).await;

        // Use global config (cached, configurable via env var)
        let config = get_config().await?;
        config.validate_paths()?;

        let result = match operation {
            "build" => self.build_project(&config, args).await,
            "clean" => self.clean_project(&config, args).await,
            "menuconfig" => self.menuconfig(&config, args).await,
            "reconfigure" => self.reconfigure(&config, args).await,
            _ => return Err(format!("Unknown operation: {}", operation)),
        };

        match &result {
            Ok(output) => {
                crate::progressbar::record_tool_complete(
                    &chat_id,
                    tool_call_id,
                    "esp32_build",
                    operation,
                    args.clone(),
                    invoked_at,
                    output,
                ).await;
            }
            Err(e) => {
                crate::progressbar::record_tool_error(
                    &chat_id,
                    tool_call_id,
                    "esp32_build",
                    operation,
                    args.clone(),
                    invoked_at,
                    e,
                ).await;
            }
        }

        let output = result?;

        let context_files = vec![ContextEnum::ChatMessage(ChatMessage {
            role: "tool".to_string(),
            content: ChatContent::SimpleText(output.to_llm_context()),
            tool_calls: None,
            tool_call_id: tool_call_id.clone(),
            ..Default::default()
        })];

        Ok((false, context_files))
    }

    fn tool_depends_on(&self) -> Vec<String> {
        vec!["esp32".to_string()]
    }
}

impl ESP32Build {
    fn config_dependency_paths(project_path: &std::path::Path) -> Vec<std::path::PathBuf> {
        let mut paths = vec![
            project_path.join("sdkconfig.defaults"),
            project_path.join("partitions.csv"),
        ];

        if let Ok(entries) = std::fs::read_dir(project_path) {
            for entry in entries.flatten() {
                let path = entry.path();
                if !path.is_file() {
                    continue;
                }
                let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
                    continue;
                };
                if file_name.starts_with("sdkconfig.defaults.") {
                    paths.push(path);
                }
            }
        }

        paths
    }

    async fn needs_reconfigure(project_path: &std::path::Path) -> bool {
        let sdkconfig_path = project_path.join("sdkconfig");
        let dependency_paths = Self::config_dependency_paths(project_path);

        let existing_dependencies: Vec<std::path::PathBuf> = dependency_paths
            .into_iter()
            .filter(|path| path.exists())
            .collect();

        if existing_dependencies.is_empty() {
            return false;
        }

        if !sdkconfig_path.exists() {
            return true;
        }

        let Ok(sdkconfig_meta) = fs::metadata(&sdkconfig_path).await else {
            return true;
        };
        let Ok(sdkconfig_modified) = sdkconfig_meta.modified() else {
            return true;
        };

        for dependency_path in existing_dependencies {
            let Ok(meta) = fs::metadata(&dependency_path).await else {
                continue;
            };
            let Ok(modified) = meta.modified() else {
                continue;
            };
            if modified > sdkconfig_modified {
                return true;
            }
        }

        false
    }

    fn parse_flash_size_bytes(size: &str) -> Option<u64> {
        let normalized = size.trim().replace(' ', "").to_uppercase();
        let (number_part, multiplier) = if let Some(value) = normalized.strip_suffix("MB") {
            (value, 1024_u64 * 1024)
        } else if let Some(value) = normalized.strip_suffix('M') {
            (value, 1024_u64 * 1024)
        } else if let Some(value) = normalized.strip_suffix("KB") {
            (value, 1024_u64)
        } else if let Some(value) = normalized.strip_suffix('K') {
            (value, 1024_u64)
        } else {
            (normalized.as_str(), 1_u64)
        };

        number_part.parse::<u64>().ok().map(|number| number * multiplier)
    }

    async fn infer_flash_size_for_recovery(config: &ESP32Config) -> String {
        let state = get_state().await;
        if let Some(active_device) = &state.session.active_device {
            if !active_device.flash_size.is_empty() && active_device.flash_size != "unknown" {
                return active_device.flash_size.clone();
            }
        }

        config.default_flash_size.clone()
    }

    async fn attempt_partition_overflow_recovery(
        &self,
        config: &ESP32Config,
        project_path: &std::path::Path,
    ) -> Result<String, String> {
        let flash_size = Self::infer_flash_size_for_recovery(config).await;
        let flash_bytes = Self::parse_flash_size_bytes(&flash_size)
            .unwrap_or(4 * 1024 * 1024);

        let request = PartitionConfigRequest {
            scheme: "huge_app".to_string(),
            flash_size: Some(flash_size.clone()),
            app_size: None,
            factory_size: None,
            filesystem: Some(if flash_bytes >= 16 * 1024 * 1024 {
                "spiffs".to_string()
            } else {
                "none".to_string()
            }),
            reconfigure: true,
            size_optimization: Some(flash_bytes < 8 * 1024 * 1024),
        };

        let applied = ESP32ConfigTool::apply_partition_configuration(config, project_path, &request).await?;

        Ok(format!(
            "Applied automatic partition recovery using {} with flash size {} and filesystem {}",
            applied.scheme, applied.flash_size, applied.filesystem
        ))
    }

    async fn build_project(&self, config: &ESP32Config, args: &HashMap<String, Value>) -> Result<ToolOutput, String> {
        // Infer project path if not provided
        let explicit_path = args.get("project_path").and_then(|v| v.as_str());
        let project_path = infer_project_path(explicit_path, None)
            .ok_or_else(|| {
                if explicit_path.is_some() {
                    format!("Provided path is not an ESP-IDF project (missing CMakeLists.txt or main/)")
                } else {
                    "No project_path provided and current directory is not an ESP-IDF project".to_string()
                }
            })?;

        if Self::needs_reconfigure(&project_path).await {
            let reconfigure_result = IdfCommand::reconfigure_fresh(config, &project_path, 120).await?;

            if !reconfigure_result.success {
                return Err(format!(
                    "Project configuration inputs changed but reconfigure failed. Please run 'idf.py reconfigure' manually. Error: {}",
                    reconfigure_result.stderr
                ));
            }
        }

        // Use IdfCommand for proper environment setup
        let mut idf_cmd = IdfCommand::new("build")
            .project_path(&project_path)
            .timeout_secs(600);  // 10 minute timeout

        if let Some(target) = args.get("target").and_then(|v| v.as_str()) {
            idf_cmd = idf_cmd.env("IDF_TARGET", target);
        }

        let mut result = idf_cmd.execute(config).await?;
        let mut recovery_note = None;

        if !result.success && result.errors.iter().any(|error| error.kind == "partition_overflow") {
            match self
                .attempt_partition_overflow_recovery(config, &project_path)
                .await
            {
                Ok(note) => {
                    recovery_note = Some(note);

                    let mut retry_cmd = IdfCommand::new("build")
                        .project_path(&project_path)
                        .timeout_secs(600);
                    if let Some(target) = args.get("target").and_then(|v| v.as_str()) {
                        retry_cmd = retry_cmd.env("IDF_TARGET", target);
                    }
                    result = retry_cmd.execute(config).await?;
                }
                Err(err) => {
                    recovery_note = Some(format!("Automatic partition recovery failed: {}", err));
                }
            }
        }
        let build_time = result.duration;

        if result.success {
            // Find binary output
            let build_dir = project_path.join("build");
            
            // Get project name from CMakeLists.txt or directory name
            let project_name = get_project_name(&project_path);
            
            // Look for the main binary (project_name.bin)
            let bin_path = build_dir.join(format!("{}.bin", project_name));
            let elf_path = build_dir.join(format!("{}.elf", project_name));
            
            let binary_info = if bin_path.exists() {
                let size = std::fs::metadata(&bin_path)
                    .map(|m| m.len() as usize)
                    .unwrap_or(0);
                serde_json::json!({
                    "binary_path": bin_path.to_string_lossy(),
                    "elf_path": elf_path.to_string_lossy(),
                    "size_bytes": size,
                    "size_kb": size / 1024,
                })
            } else {
                // Fallback: find any .bin file
                let fallback_bin = std::fs::read_dir(&build_dir)
                    .ok()
                    .and_then(|entries| {
                        entries.filter_map(|e| e.ok())
                            .find(|e| e.path().extension().map(|ext| ext == "bin").unwrap_or(false))
                            .map(|e| e.path())
                    });
                
                if let Some(bin) = fallback_bin {
                    let size = std::fs::metadata(&bin).map(|m| m.len() as usize).unwrap_or(0);
                    serde_json::json!({
                        "binary_path": bin.to_string_lossy(),
                        "size_bytes": size,
                        "size_kb": size / 1024,
                    })
                } else {
                    serde_json::json!({})
                }
            };

            // Generate suggested actions for successful build
            let suggested_actions = generate_suggested_actions(
                "build",
                true,
                &SuggestionContext::new(),
            );

            Ok(ToolOutput {
                status: super::output_protocol::ToolStatus::Success,
                action_taken: "build".to_string(),
                data: serde_json::json!({
                    "status": "success",
                    "build_time_seconds": build_time.as_secs_f64(),
                    "binary": binary_info,
                    "project_path": project_path.to_string_lossy(),
                    "automatic_recovery": recovery_note.clone(),
                }),
                summary: match &recovery_note {
                    Some(note) => format!(
                        "Built successfully in {:.1}s after automatic recovery. {}",
                        build_time.as_secs_f64(),
                        note
                    ),
                    None => format!("Built successfully in {:.1}s", build_time.as_secs_f64()),
                },
                details: None,
                state_delta: super::session_state::StateDelta::none(),
                suggested_actions,
                error: None,
            })
        } else {
            // Use pre-parsed errors from IdfCommand (Cursor-style structured diagnostics)
            let error = result.errors.first().cloned();
            let has_missing_component = result.errors.iter()
                .any(|e| e.subcategory.contains("component"));

            // Generate suggested actions for failed build
            let mut ctx = SuggestionContext::new();
            if has_missing_component {
                ctx = ctx.with_missing_component();
            }
            let suggested_actions = generate_suggested_actions("build", false, &ctx);

            // Build structured error data for the LLM — capped at 3 to save context
            // (fix the first error; subsequent ones usually cascade from it).
            // The `details` field already formats these via format_error_diagnostics(3).
            const MAX_ERRORS_IN_JSON: usize = 3;
            let errors_json: Vec<serde_json::Value> = result.errors.iter().take(MAX_ERRORS_IN_JSON).map(|e| {
                let mut obj = serde_json::json!({
                    "kind": e.kind,
                    "message": e.message,
                    "severity": format!("{:?}", e.severity),
                    "phase": e.phase,
                    "likely_cause": e.likely_cause,
                });
                if let Some(ref f) = e.file {
                    obj["file"] = serde_json::json!(f);
                }
                if let Some(l) = e.line {
                    obj["line"] = serde_json::json!(l);
                }
                if let Some(ref patch) = e.suggested_patch {
                    obj["suggested_patch"] = serde_json::json!({
                        "file": patch.file,
                        "action": patch.action,
                    });
                }
                obj
            }).collect();

            // Format top 3 errors as Cursor-style diagnostic block for details
            let diagnostics_text = super::output_protocol::format_error_diagnostics(&result.errors, 3);

            Ok(ToolOutput {
                status: super::output_protocol::ToolStatus::Failed,
                action_taken: "build".to_string(),
                data: serde_json::json!({
                    "status": "failed",
                    "total_error_count": result.errors.len(),
                    "shown_errors": errors_json.len(),
                    "summary": result.summary,
                    "project_path": project_path.to_string_lossy(),
                    "errors": errors_json,
                    "automatic_recovery": recovery_note.clone(),
                }),
                summary: format!("Build failed: {}", result.summary),
                details: Some(match &recovery_note {
                    Some(note) => format!("{}\n\nAutomatic recovery attempted: {}", diagnostics_text, note),
                    None => diagnostics_text,
                }),
                state_delta: super::session_state::StateDelta::none(),
                suggested_actions,
                error,
            })
        }
    }

    async fn clean_project(&self, config: &ESP32Config, args: &HashMap<String, Value>) -> Result<ToolOutput, String> {
        let explicit_path = args.get("project_path").and_then(|v| v.as_str());
        let project_path = infer_project_path(explicit_path, None)
            .ok_or("No valid ESP-IDF project found")?;

        let result = IdfCommand::new("fullclean")
            .project_path(&project_path)
            .timeout_secs(60)
            .execute(config).await?;

        if result.success {
            Ok(ToolOutput::success(
                "Project cleaned successfully".to_string(),
                serde_json::json!({
                    "project_path": project_path.to_string_lossy(),
                }),
            ))
        } else {
            Err(format!("Clean failed: {}", result.stderr))
        }
    }

    async fn menuconfig(&self, config: &ESP32Config, args: &HashMap<String, Value>) -> Result<ToolOutput, String> {
        // menuconfig is interactive, but we can show current config summary
        let explicit_path = args.get("project_path").and_then(|v| v.as_str());
        
        if let Some(project_path) = infer_project_path(explicit_path, None) {
            // Only check sdkconfig.defaults, not autogenerated sdkconfig (too large)
            let defaults_path = project_path.join("sdkconfig.defaults");
            if defaults_path.exists() {
                // Read and summarize key config values from defaults only
                if let Ok(content) = std::fs::read_to_string(&defaults_path) {
                    let key_configs: Vec<&str> = content.lines()
                        .filter(|line| {
                            line.starts_with("CONFIG_IDF_TARGET=") ||
                            line.starts_with("CONFIG_ESPTOOLPY_") ||
                            line.starts_with("CONFIG_PARTITION_TABLE") ||
                            line.starts_with("CONFIG_ESP_WIFI") ||
                            line.starts_with("CONFIG_FREERTOS")
                        })
                        .take(10)
                        .collect();
                    
                    return Ok(ToolOutput {
                        status: super::output_protocol::ToolStatus::PartialSuccess,
                        action_taken: "menuconfig".to_string(),
                        data: serde_json::json!({
                            "interactive": true,
                            "key_configs": key_configs,
                            "total_lines": content.lines().count(),
                        }),
                        summary: "menuconfig is interactive. Key config values shown below. Run 'idf.py menuconfig' manually to modify.".to_string(),
                        details: Some(key_configs.join("\n")),
                        state_delta: super::session_state::StateDelta::none(),
                        suggested_actions: vec![],
                        error: None,
                    });
                }
            }
        }
        
        Ok(ToolOutput {
            status: super::output_protocol::ToolStatus::Skipped,
            action_taken: "menuconfig".to_string(),
            data: serde_json::json!({"interactive": true}),
            summary: "menuconfig is interactive - run 'idf.py menuconfig' manually".to_string(),
            details: None,
            state_delta: super::session_state::StateDelta::none(),
            suggested_actions: vec![],
            error: None,
        })
    }

    async fn reconfigure(&self, config: &ESP32Config, args: &HashMap<String, Value>) -> Result<ToolOutput, String> {
        let explicit_path = args.get("project_path").and_then(|v| v.as_str());
        let project_path = infer_project_path(explicit_path, None)
            .ok_or("No valid ESP-IDF project found")?;

        // Check if sdkconfig.defaults exists and provide context
        let defaults_path = project_path.join("sdkconfig.defaults");
        let has_defaults = defaults_path.exists();
        
        let mut summary_parts = vec![];
        if has_defaults {
            // Check if defaults file was recently modified (within last 5 minutes)
            if let Ok(metadata) = fs::metadata(&defaults_path).await {
                if let Ok(modified) = metadata.modified() {
                    let age = std::time::SystemTime::now()
                        .duration_since(modified)
                        .unwrap_or_default();
                    if age.as_secs() < 300 {
                        summary_parts.push("sdkconfig.defaults was recently modified".to_string());
                    }
                }
            }
            summary_parts.push("Propagating sdkconfig.defaults to autogenerated sdkconfig".to_string());
        } else {
            summary_parts.push("No sdkconfig.defaults found - regenerating sdkconfig from Kconfig defaults".to_string());
        }

        let result = IdfCommand::reconfigure_fresh(config, &project_path, 120).await?;

        if result.success {
            let summary = if summary_parts.is_empty() {
                "Project reconfigured successfully".to_string()
            } else {
                format!("Project reconfigured successfully. {}", summary_parts.join(". "))
            };

            Ok(ToolOutput::success(
                summary,
                serde_json::json!({
                    "project_path": project_path.to_string_lossy(),
                    "has_defaults": has_defaults,
                    "action": "Propagated sdkconfig.defaults to sdkconfig",
                }),
            ))
        } else {
            let error_msg = if has_defaults {
                format!(
                    "Reconfigure failed while propagating sdkconfig.defaults to sdkconfig. This ensures changes in sdkconfig.defaults are applied to the generated sdkconfig file. Error: {}",
                    result.stderr
                )
            } else {
                format!("Reconfigure failed: {}", result.stderr)
            };
            Err(error_msg)
        }
    }
}

