use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;
use serde_json::Value;
use tokio::sync::Mutex as AMutex;

use crate::at_commands::at_commands::AtCommandsContext;
use crate::tools::tools_description::{Tool, ToolDesc, ToolParam, ToolSource, ToolSourceType};
use crate::call_validation::{ChatMessage, ChatContent, ContextEnum};

use super::config::ESP32Config;
use super::output_protocol::ToolOutput;
use super::global_state::get_config;
use super::idf_command::IdfCommand;
use super::board_definition::BoardDefinition;
use super::global_state::{get_state, get_state_mut, board_definition_url, resolve_device_port};
use super::device_port_store::PortResolutionPolicy;

pub struct ESP32ConfigTool {
    pub config_path: String,
}

pub(crate) struct PartitionConfigRequest {
    pub scheme: String,
    pub flash_size: Option<String>,
    pub app_size: Option<String>,
    pub factory_size: Option<String>,
    pub filesystem: Option<String>,
    pub reconfigure: bool,
    pub size_optimization: Option<bool>,
}

pub(crate) struct PartitionApplyResult {
    pub defaults_path: std::path::PathBuf,
    pub partitions_path: std::path::PathBuf,
    pub scheme: String,
    pub flash_size: String,
    pub filesystem: String,
    pub reconfigured: bool,
}

#[async_trait]
impl Tool for ESP32ConfigTool {
    fn as_any(&self) -> &dyn std::any::Any { self }

    fn tool_description(&self) -> ToolDesc {
        ToolDesc {
            name: "esp32_config".to_string(),
            display_name: "ESP32 Config".to_string(),
            source: ToolSource {
                source_type: ToolSourceType::Builtin,
                config_path: self.config_path.clone(),
            },
            agentic: true,
            experimental: false,
            description: "Configure ESP32 project settings. Operations: sdkconfig (modify Kconfig options), auto_configure (auto-generate sdkconfig.defaults from connected device), preset (apply board presets like wifi_remote_func_ev), partition (manage partition tables), wifi (configure Wi-Fi), gpio (configure GPIO pins), show (display current configuration). IMPORTANT: Never open or edit the full autogenerated sdkconfig. Make changes only via sdkconfig.defaults (or sdkconfig.defaults.*). If verification is required, extract only specific CONFIG_ entries from sdkconfig (e.g., via grep), never the whole file.".to_string(),
            parameters: vec![
                ToolParam {
                    name: "operation".to_string(),
                    param_type: "string".to_string(),
                    description: "Operation: 'sdkconfig' (modify Kconfig), 'auto_configure' (auto-generate defaults from device), 'preset' (apply board presets like 'wifi_remote_func_ev'), 'partition' (partition table), 'wifi' (Wi-Fi settings), 'gpio' (GPIO config), 'show' (display config)".to_string(),
                },
                ToolParam {
                    name: "port".to_string(),
                    param_type: "string".to_string(),
                    description: "Serial port for device operations (e.g., /dev/ttyUSB0). Required for 'auto_configure'.".to_string(),
                },
                ToolParam {
                    name: "reconfigure".to_string(),
                    param_type: "boolean".to_string(),
                    description: "Run 'idf.py reconfigure' after modifying config (default: true for sdkconfig, auto_configure, partition, wifi, and preset)".to_string(),
                },
                ToolParam {
                    name: "project_path".to_string(),
                    param_type: "string".to_string(),
                    description: "Path to ESP32 project".to_string(),
                },
                ToolParam {
                    name: "key".to_string(),
                    param_type: "string".to_string(),
                    description: "Configuration key (e.g., 'CONFIG_ESP_WIFI_SSID')".to_string(),
                },
                ToolParam {
                    name: "value".to_string(),
                    param_type: "string".to_string(),
                    description: "Value to set".to_string(),
                },
                ToolParam {
                    name: "board_id".to_string(),
                    param_type: "string".to_string(),
                    description: "Board ID for schema-based preset/application".to_string(),
                },
                ToolParam {
                    name: "preset_name".to_string(),
                    param_type: "string".to_string(),
                    description: "Preset name for 'preset' operation (e.g., 'wifi_remote_func_ev' for ESP32-P4 Function-EV board Wi-Fi Remote setup)".to_string(),
                },
                ToolParam {
                    name: "scheme".to_string(),
                    param_type: "string".to_string(),
                    description: "Partition scheme for 'partition': 'huge_app', 'ota_2app', or 'custom'".to_string(),
                },
                ToolParam {
                    name: "flash_size".to_string(),
                    param_type: "string".to_string(),
                    description: "Flash size for 'partition' (e.g., '4MB', '8MB', '16MB')".to_string(),
                },
                ToolParam {
                    name: "app_size".to_string(),
                    param_type: "string".to_string(),
                    description: "App partition size for OTA or custom partition layouts (e.g., '2M', '4M')".to_string(),
                },
                ToolParam {
                    name: "factory_size".to_string(),
                    param_type: "string".to_string(),
                    description: "Factory app partition size for single-app layouts (e.g., '6M')".to_string(),
                },
                ToolParam {
                    name: "filesystem".to_string(),
                    param_type: "string".to_string(),
                    description: "Filesystem type for 'partition': 'spiffs', 'littlefs', or 'none'".to_string(),
                },
                ToolParam {
                    name: "size_optimization".to_string(),
                    param_type: "boolean".to_string(),
                    description: "Enable CONFIG_COMPILER_OPTIMIZATION_SIZE during partition changes".to_string(),
                },
            ],
            parameters_required: vec!["operation".to_string()],
        }
    }

    async fn tool_execute(
        &mut self,
        ccx: Arc<AMutex<AtCommandsContext>>,
        tool_call_id: &String,
        args: &HashMap<String, Value>,
    ) -> Result<(bool, Vec<ContextEnum>), String> {
        let operation = args.get("operation")
            .and_then(|v| v.as_str())
            .ok_or("Missing required parameter: operation")?;

        let chat_id = ccx.lock().await.chat_id.clone();
        let invoked_at = std::time::SystemTime::now();
        crate::progressbar::record_tool_start(
            &chat_id,
            tool_call_id,
            "esp32_config",
            operation,
            args.clone(),
        ).await;

        // Use global config (cached, configurable via env var)
        let config = get_config().await?;

        let result = match operation {
            "sdkconfig" => self.modify_sdkconfig(&config, args).await,
            "auto_configure" => self.auto_configure_from_device(&config, args).await,
            "preset" => self.apply_preset(&config, args).await,
            "partition" => self.manage_partition(&config, args).await,
            "wifi" => self.configure_wifi(&config, args).await,
            "gpio" => self.configure_gpio(&config, args).await,
            "show" => self.show_config(&config, args).await,
            _ => return Err(format!("Unknown operation: {}", operation)),
        };

        match &result {
            Ok(output) => {
                crate::progressbar::record_tool_complete(
                    &chat_id,
                    tool_call_id,
                    "esp32_config",
                    operation,
                    args.clone(),
                    invoked_at,
                    output,
                ).await;
            }
            Err(e) => {
                crate::progressbar::record_tool_error(
                    &chat_id,
                    tool_call_id,
                    "esp32_config",
                    operation,
                    args.clone(),
                    invoked_at,
                    e,
                ).await;
            }
        }

        let output = result?;

        let context_files = vec![ContextEnum::ChatMessage(ChatMessage {
            role: "tool".to_string(),
            content: ChatContent::SimpleText(output.to_llm_context()),
            tool_calls: None,
            tool_call_id: tool_call_id.clone(),
            ..Default::default()
        })];

        Ok((false, context_files))
    }

    fn tool_depends_on(&self) -> Vec<String> {
        vec!["esp32".to_string()]
    }
}

impl ESP32ConfigTool {
    /// Format a value for Kconfig: string values must be double-quoted per ESP-IDF Kconfig.
    fn format_kconfig_value(value: &str) -> String {
        if value == "y" || value == "n" || value == "m" {
            return value.to_string();
        }
        if value.parse::<i64>().is_ok() {
            return value.to_string();
        }
        if value.starts_with('"') && value.ends_with('"') && value.len() >= 2 {
            return value.to_string();
        }
        format!("\"{}\"", value)
    }

    fn matches_kconfig_key(line: &str, key: &str) -> bool {
        let trimmed = line.trim();
        trimmed.starts_with(&format!("{}=", key)) || trimmed == format!("# {} is not set", key)
    }

    fn remove_kconfig_key(lines: &mut Vec<String>, key: &str) {
        lines.retain(|line| !Self::matches_kconfig_key(line, key));
    }

    fn remove_kconfig_prefix(lines: &mut Vec<String>, prefix: &str) {
        lines.retain(|line| {
            let trimmed = line.trim();
            !(trimmed.starts_with(prefix)
                || (trimmed.starts_with("# ") && trimmed[2..].starts_with(prefix)))
        });
    }

    fn set_kconfig_value(lines: &mut Vec<String>, key: &str, value: &str) {
        let value_formatted = Self::format_kconfig_value(value);
        Self::remove_kconfig_key(lines, key);
        lines.push(format!("{}={}", key, value_formatted));
    }

    fn clear_mutually_exclusive_keys(lines: &mut Vec<String>, key: &str) {
        if key.starts_with("CONFIG_ESPTOOLPY_FLASHSIZE_") {
            Self::remove_kconfig_prefix(lines, "CONFIG_ESPTOOLPY_FLASHSIZE_");
        }

        if key == "CONFIG_PARTITION_TABLE_CUSTOM" {
            for partition_key in [
                "CONFIG_PARTITION_TABLE_SINGLE_APP",
                "CONFIG_PARTITION_TABLE_TWO_OTA",
                "CONFIG_PARTITION_TABLE_TWO_OTA_LARGE",
                "CONFIG_PARTITION_TABLE_HUGE_APP",
                "CONFIG_PARTITION_TABLE_CUSTOM",
            ] {
                Self::remove_kconfig_key(lines, partition_key);
            }
        }

        if key == "CONFIG_COMPILER_OPTIMIZATION_SIZE" {
            for optimization_key in [
                "CONFIG_COMPILER_OPTIMIZATION_DEFAULT",
                "CONFIG_COMPILER_OPTIMIZATION_DEBUG",
                "CONFIG_COMPILER_OPTIMIZATION_NONE",
                "CONFIG_COMPILER_OPTIMIZATION_PERF",
                "CONFIG_COMPILER_OPTIMIZATION_SIZE",
            ] {
                Self::remove_kconfig_key(lines, optimization_key);
            }
        }
    }

    fn parse_kconfig_value(contents: &str, key: &str) -> Option<String> {
        contents.lines().find_map(|line| {
            let trimmed = line.trim();
            if !trimmed.starts_with(&format!("{}=", key)) {
                return None;
            }

            let (_, raw_value) = trimmed.split_once('=')?;
            Some(raw_value.trim().trim_matches('"').to_string())
        })
    }

    fn detect_project_target(project_path: &std::path::Path) -> Option<String> {
        let generic_defaults = project_path.join("sdkconfig.defaults");
        if generic_defaults.exists() {
            if let Ok(contents) = std::fs::read_to_string(&generic_defaults) {
                if let Some(target) = Self::parse_kconfig_value(&contents, "CONFIG_IDF_TARGET") {
                    return Some(target);
                }
            }
        }

        let sdkconfig = project_path.join("sdkconfig");
        if sdkconfig.exists() {
            if let Ok(contents) = std::fs::read_to_string(&sdkconfig) {
                if let Some(target) = Self::parse_kconfig_value(&contents, "CONFIG_IDF_TARGET") {
                    return Some(target);
                }
            }
        }

        None
    }

    pub(crate) fn resolve_defaults_path(project_path: &std::path::Path) -> std::path::PathBuf {
        if let Some(target) = Self::detect_project_target(project_path) {
            let target_defaults = project_path.join(format!("sdkconfig.defaults.{}", target));
            if target_defaults.exists() {
                return target_defaults;
            }
        }

        let mut discovered_target_defaults = Vec::new();
        if let Ok(entries) = std::fs::read_dir(project_path) {
            for entry in entries.flatten() {
                let path = entry.path();
                if !path.is_file() {
                    continue;
                }
                let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
                    continue;
                };
                if file_name.starts_with("sdkconfig.defaults.") {
                    discovered_target_defaults.push(path);
                }
            }
        }

        if discovered_target_defaults.len() == 1 {
            return discovered_target_defaults.remove(0);
        }

        project_path.join("sdkconfig.defaults")
    }

    async fn read_defaults_lines(
        project_path: &std::path::Path,
    ) -> Result<(std::path::PathBuf, Vec<String>), String> {
        let defaults_path = Self::resolve_defaults_path(project_path);
        let content = if defaults_path.exists() {
            tokio::fs::read_to_string(&defaults_path)
                .await
                .map_err(|e| format!("Failed to read {}: {}", defaults_path.display(), e))?
        } else {
            String::new()
        };

        Ok((
            defaults_path,
            content.lines().map(|line| line.to_string()).collect(),
        ))
    }

    pub(crate) async fn update_sdkconfig_defaults(
        project_path: &std::path::Path,
        values: &[(String, String)],
    ) -> Result<std::path::PathBuf, String> {
        let (defaults_path, mut lines) = Self::read_defaults_lines(project_path).await?;

        for (key, value) in values {
            Self::clear_mutually_exclusive_keys(&mut lines, key);
            Self::set_kconfig_value(&mut lines, key, value);
        }

        tokio::fs::write(&defaults_path, lines.join("\n"))
            .await
            .map_err(|e| format!("Failed to write {}: {}", defaults_path.display(), e))?;

        Ok(defaults_path)
    }

    fn parse_size_bytes(size: &str) -> Result<u64, String> {
        let normalized = size.trim().replace(' ', "").to_uppercase();
        if normalized.is_empty() {
            return Err("Size value cannot be empty".to_string());
        }

        let (number_part, multiplier) = if let Some(value) = normalized.strip_suffix("MB") {
            (value, 1024_u64 * 1024)
        } else if let Some(value) = normalized.strip_suffix('M') {
            (value, 1024_u64 * 1024)
        } else if let Some(value) = normalized.strip_suffix("KB") {
            (value, 1024_u64)
        } else if let Some(value) = normalized.strip_suffix('K') {
            (value, 1024_u64)
        } else if let Some(value) = normalized.strip_suffix('B') {
            (value, 1_u64)
        } else {
            (normalized.as_str(), 1_u64)
        };

        let number = number_part
            .parse::<u64>()
            .map_err(|_| format!("Invalid size value: {}", size))?;
        Ok(number * multiplier)
    }

    fn format_partition_size(bytes: u64) -> String {
        if bytes % (1024 * 1024) == 0 {
            format!("{}M", bytes / (1024 * 1024))
        } else if bytes % 1024 == 0 {
            format!("{}K", bytes / 1024)
        } else {
            bytes.to_string()
        }
    }

    async fn infer_flash_size_from_config_or_session(config: &ESP32Config) -> String {
        let state = get_state().await;
        if let Some(active_device) = &state.session.active_device {
            if !active_device.flash_size.is_empty() && active_device.flash_size != "unknown" {
                return active_device.flash_size.clone();
            }
        }

        config.default_flash_size.clone()
    }

    pub(crate) async fn apply_partition_configuration(
        config: &ESP32Config,
        project_path: &std::path::Path,
        request: &PartitionConfigRequest,
    ) -> Result<PartitionApplyResult, String> {
        let scheme = request.scheme.trim().to_lowercase();
        let flash_size = request
            .flash_size
            .clone()
            .unwrap_or_else(|| config.default_flash_size.clone());
        let flash_size = if request.flash_size.is_some() {
            flash_size
        } else {
            Self::infer_flash_size_from_config_or_session(config).await
        };
        let flash_bytes = Self::parse_size_bytes(&flash_size)?;
        let filesystem = request.filesystem.as_deref().unwrap_or("spiffs").to_lowercase();
        let include_filesystem = filesystem != "none";
        let include_ota = scheme == "ota_2app";

        let reserved_bytes = 0x9000_u64 + if include_ota { 0x2000 } else { 0 } + 0x1000;
        let default_filesystem_bytes = if include_filesystem {
            if flash_bytes >= 8 * 1024 * 1024 {
                1024 * 1024
            } else {
                512 * 1024
            }
        } else {
            0
        };

        let app_size_bytes = request
            .app_size
            .as_deref()
            .map(Self::parse_size_bytes)
            .transpose()?;
        let factory_size_bytes = request
            .factory_size
            .as_deref()
            .map(Self::parse_size_bytes)
            .transpose()?;

        let partition_rows = match scheme.as_str() {
            "huge_app" => {
                let filesystem_bytes = if include_filesystem {
                    default_filesystem_bytes
                } else {
                    0
                };
                let factory_bytes = factory_size_bytes
                    .or(app_size_bytes)
                    .unwrap_or_else(|| flash_bytes.saturating_sub(reserved_bytes + filesystem_bytes));
                if factory_bytes == 0 || reserved_bytes + filesystem_bytes + factory_bytes > flash_bytes {
                    return Err("Requested huge_app layout does not fit into flash".to_string());
                }

                let mut rows = vec![
                    "nvs,data,nvs,,36K,".to_string(),
                    "phy_init,data,phy,,4K,".to_string(),
                    format!(
                        "factory,app,factory,,{},",
                        Self::format_partition_size(factory_bytes)
                    ),
                ];
                if include_filesystem {
                    let storage_bytes = flash_bytes - reserved_bytes - factory_bytes;
                    if storage_bytes > 0 {
                        rows.push(format!(
                            "storage,data,{},{},{},",
                            filesystem,
                            "",
                            Self::format_partition_size(storage_bytes)
                        ));
                    }
                }
                rows
            }
            "ota_2app" => {
                let filesystem_bytes = if include_filesystem {
                    default_filesystem_bytes
                } else {
                    0
                };
                let available_for_apps = flash_bytes.saturating_sub(reserved_bytes + filesystem_bytes);
                let per_app_bytes = app_size_bytes.unwrap_or(available_for_apps / 2);
                if per_app_bytes == 0 || reserved_bytes + filesystem_bytes + (per_app_bytes * 2) > flash_bytes {
                    return Err("Requested ota_2app layout does not fit into flash".to_string());
                }

                let mut rows = vec![
                    "nvs,data,nvs,,36K,".to_string(),
                    "otadata,data,ota,,8K,".to_string(),
                    "phy_init,data,phy,,4K,".to_string(),
                    format!(
                        "ota_0,app,ota_0,,{},",
                        Self::format_partition_size(per_app_bytes)
                    ),
                    format!(
                        "ota_1,app,ota_1,,{},",
                        Self::format_partition_size(per_app_bytes)
                    ),
                ];
                if include_filesystem {
                    let storage_bytes = flash_bytes - reserved_bytes - (per_app_bytes * 2);
                    if storage_bytes > 0 {
                        rows.push(format!(
                            "storage,data,{},{},{},",
                            filesystem,
                            "",
                            Self::format_partition_size(storage_bytes)
                        ));
                    }
                }
                rows
            }
            "custom" => {
                let include_ota_custom = request.app_size.is_some() && request.factory_size.is_none();
                let reserved_bytes = 0x9000_u64 + if include_ota_custom { 0x2000 } else { 0 } + 0x1000;
                let filesystem_bytes = if include_filesystem {
                    flash_bytes.saturating_sub(
                        reserved_bytes
                            + if include_ota_custom {
                                app_size_bytes.unwrap_or(0) * 2
                            } else {
                                factory_size_bytes.or(app_size_bytes).unwrap_or(0)
                            },
                    )
                } else {
                    0
                };

                let mut rows = vec![
                    "nvs,data,nvs,,36K,".to_string(),
                ];
                if include_ota_custom {
                    let app_bytes = app_size_bytes.ok_or(
                        "Custom OTA layout requires app_size (for both ota slots)",
                    )?;
                    if reserved_bytes + (app_bytes * 2) > flash_bytes {
                        return Err("Requested custom OTA layout does not fit into flash".to_string());
                    }
                    rows.push("otadata,data,ota,,8K,".to_string());
                    rows.push("phy_init,data,phy,,4K,".to_string());
                    rows.push(format!(
                        "ota_0,app,ota_0,,{},",
                        Self::format_partition_size(app_bytes)
                    ));
                    rows.push(format!(
                        "ota_1,app,ota_1,,{},",
                        Self::format_partition_size(app_bytes)
                    ));
                } else {
                    let factory_bytes = factory_size_bytes
                        .or(app_size_bytes)
                        .ok_or("Custom factory layout requires factory_size or app_size")?;
                    if reserved_bytes + factory_bytes > flash_bytes {
                        return Err("Requested custom factory layout does not fit into flash".to_string());
                    }
                    rows.push("phy_init,data,phy,,4K,".to_string());
                    rows.push(format!(
                        "factory,app,factory,,{},",
                        Self::format_partition_size(factory_bytes)
                    ));
                }

                if include_filesystem && filesystem_bytes > 0 {
                    rows.push(format!(
                        "storage,data,{},{},{},",
                        filesystem,
                        "",
                        Self::format_partition_size(filesystem_bytes)
                    ));
                }
                rows
            }
            _ => {
                return Err(format!(
                    "Unsupported partition scheme: {}. Supported schemes: huge_app, ota_2app, custom",
                    request.scheme
                ))
            }
        };

        let partitions_csv = format!(
            "# Name, Type, SubType, Offset, Size, Flags\n{}\n",
            partition_rows.join("\n")
        );
        let partitions_path = project_path.join("partitions.csv");
        tokio::fs::write(&partitions_path, partitions_csv)
            .await
            .map_err(|e| format!("Failed to write {}: {}", partitions_path.display(), e))?;

        let mut updates = vec![
            ("CONFIG_PARTITION_TABLE_CUSTOM".to_string(), "y".to_string()),
            (
                "CONFIG_PARTITION_TABLE_CUSTOM_FILENAME".to_string(),
                "partitions.csv".to_string(),
            ),
        ];
        let normalized_flash = flash_size.trim().replace(' ', "").to_uppercase();
        updates.push((
            format!("CONFIG_ESPTOOLPY_FLASHSIZE_{}", normalized_flash),
            "y".to_string(),
        ));
        if request.size_optimization.unwrap_or(false) {
            updates.push((
                "CONFIG_COMPILER_OPTIMIZATION_SIZE".to_string(),
                "y".to_string(),
            ));
        }

        let defaults_path = Self::update_sdkconfig_defaults(project_path, &updates).await?;

        if request.reconfigure {
            let result = IdfCommand::reconfigure_fresh(config, project_path, 120).await?;
            if !result.success {
                return Err(format!("Reconfigure failed: {}", result.stderr));
            }
        }

        Ok(PartitionApplyResult {
            defaults_path,
            partitions_path,
            scheme: request.scheme.clone(),
            flash_size,
            filesystem: filesystem.to_string(),
            reconfigured: request.reconfigure,
        })
    }

    async fn modify_sdkconfig(&self, config: &ESP32Config, args: &HashMap<String, Value>) -> Result<ToolOutput, String> {
        let project_path = args.get("project_path")
            .and_then(|v| v.as_str())
            .map(|s| std::path::PathBuf::from(s))
            .unwrap_or_else(|| std::path::PathBuf::from("."));

        let key = args.get("key")
            .and_then(|v| v.as_str())
            .ok_or("Missing required parameter: key")?;

        let value = args.get("value")
            .and_then(|v| v.as_str())
            .ok_or("Missing required parameter: value")?;
        let defaults_path = Self::update_sdkconfig_defaults(
            &project_path,
            &[(key.to_string(), value.to_string())],
        )
        .await?;

        // Automatically trigger reconfigure to apply changes (default: true)
        // This ensures sdkconfig.defaults changes are propagated to autogenerated sdkconfig
        let reconfigure = args.get("reconfigure")
            .and_then(|v| v.as_bool())
            .unwrap_or(true);

        let reconfigure_msg = if reconfigure {
            let result = IdfCommand::reconfigure_fresh(config, &project_path, 60).await?;
            
            if !result.success {
                return Err(format!("Reconfigure failed: {}", result.stderr));
            }
            " (reconfigured)"
        } else {
            " (run 'idf.py reconfigure' to apply)"
        };

        Ok(ToolOutput::success(
            format!(
                "Set {}={} in {}{}",
                key,
                Self::format_kconfig_value(value),
                defaults_path
                    .file_name()
                    .and_then(|name| name.to_str())
                    .unwrap_or("sdkconfig.defaults"),
                reconfigure_msg
            ),
            serde_json::json!({
                "key": key,
                "value": Self::format_kconfig_value(value),
                "file": defaults_path.file_name().and_then(|name| name.to_str()).unwrap_or("sdkconfig.defaults"),
                "reconfigured": reconfigure,
            }),
        ))
    }

    async fn manage_partition(&self, config: &ESP32Config, args: &HashMap<String, Value>) -> Result<ToolOutput, String> {
        let project_path = args.get("project_path")
            .and_then(|v| v.as_str())
            .map(|s| std::path::PathBuf::from(s))
            .unwrap_or_else(|| std::path::PathBuf::from("."));

        let scheme = args.get("scheme")
            .and_then(|v| v.as_str())
            .unwrap_or("huge_app")
            .to_string();
        let request = PartitionConfigRequest {
            scheme: scheme.clone(),
            flash_size: args.get("flash_size").and_then(|v| v.as_str()).map(|s| s.to_string()),
            app_size: args.get("app_size").and_then(|v| v.as_str()).map(|s| s.to_string()),
            factory_size: args.get("factory_size").and_then(|v| v.as_str()).map(|s| s.to_string()),
            filesystem: args.get("filesystem").and_then(|v| v.as_str()).map(|s| s.to_string()),
            reconfigure: args.get("reconfigure").and_then(|v| v.as_bool()).unwrap_or(true),
            size_optimization: args.get("size_optimization").and_then(|v| v.as_bool()),
        };

        let applied = Self::apply_partition_configuration(config, &project_path, &request).await?;

        Ok(ToolOutput::success(
            format!(
                "Applied {} partition layout using {}{}",
                applied.scheme,
                applied.defaults_path
                    .file_name()
                    .and_then(|name| name.to_str())
                    .unwrap_or("sdkconfig.defaults"),
                if applied.reconfigured { " (reconfigured)" } else { "" }
            ),
            serde_json::json!({
                "scheme": applied.scheme,
                "flash_size": applied.flash_size,
                "filesystem": applied.filesystem,
                "partitions_file": applied.partitions_path.to_string_lossy(),
                "defaults_file": applied.defaults_path.file_name().and_then(|name| name.to_str()).unwrap_or("sdkconfig.defaults"),
                "reconfigured": applied.reconfigured,
            }),
        ))
    }

    async fn configure_wifi(&self, config: &ESP32Config, args: &HashMap<String, Value>) -> Result<ToolOutput, String> {
        let project_path = args.get("project_path")
            .and_then(|v| v.as_str())
            .map(|s| std::path::PathBuf::from(s))
            .unwrap_or_else(|| std::path::PathBuf::from("."));

        let ssid = args.get("ssid")
            .and_then(|v| v.as_str())
            .ok_or("Missing required parameter: ssid")?;

        let password = args.get("password")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        // Set Wi-Fi config via sdkconfig.defaults
        let defaults_path = project_path.join("sdkconfig.defaults");
        let content = if defaults_path.exists() {
            tokio::fs::read_to_string(&defaults_path).await
                .map_err(|e| format!("Failed to read sdkconfig.defaults: {}", e))?
        } else {
            String::new()
        };

        let mut lines: Vec<String> = content.lines().map(|s| s.to_string()).collect();

        // Enable Wi-Fi
        if !content.contains("CONFIG_ESP_WIFI_ENABLED=y") {
            lines.push("CONFIG_ESP_WIFI_ENABLED=y".to_string());
        }

        // Write SSID and password to sdkconfig.defaults (Kconfig string values must be quoted)
        let ssid_formatted = Self::format_kconfig_value(ssid);
        let password_formatted = Self::format_kconfig_value(password);
        for line in &mut lines {
            if line.starts_with("CONFIG_ESP_WIFI_SSID=") {
                *line = format!("CONFIG_ESP_WIFI_SSID={}", ssid_formatted);
                break;
            }
        }
        if !lines.iter().any(|l| l.starts_with("CONFIG_ESP_WIFI_SSID=")) {
            lines.push(format!("CONFIG_ESP_WIFI_SSID={}", ssid_formatted));
        }
        for line in &mut lines {
            if line.starts_with("CONFIG_ESP_WIFI_PASSWORD=") {
                *line = format!("CONFIG_ESP_WIFI_PASSWORD={}", password_formatted);
                break;
            }
        }
        if !lines.iter().any(|l| l.starts_with("CONFIG_ESP_WIFI_PASSWORD=")) {
            lines.push(format!("CONFIG_ESP_WIFI_PASSWORD={}", password_formatted));
        }

        tokio::fs::write(&defaults_path, lines.join("\n")).await
            .map_err(|e| format!("Failed to write sdkconfig.defaults: {}", e))?;

        // Optionally run idf.py reconfigure to apply sdkconfig.defaults to autogenerated sdkconfig
        let reconfigure = args.get("reconfigure")
            .and_then(|v| v.as_bool())
            .unwrap_or(true);

        let reconfigure_msg = if reconfigure {
            let result = IdfCommand::reconfigure_fresh(config, &project_path, 60).await?;
            if !result.success {
                return Err(format!("Reconfigure failed: {}", result.stderr));
            }
            " (reconfigured)"
        } else {
            " (run 'idf.py reconfigure' to apply)"
        };

        Ok(ToolOutput::success(
            format!("Wi-Fi configured: SSID={}{}", ssid, reconfigure_msg),
            serde_json::json!({
                "ssid": ssid,
                "wifi_enabled": true,
                "reconfigured": reconfigure,
            }),
        ))
    }

    async fn configure_gpio(&self, _config: &ESP32Config, _args: &HashMap<String, Value>) -> Result<ToolOutput, String> {
        // TODO: Implement GPIO configuration
        Ok(ToolOutput {
            status: super::output_protocol::ToolStatus::Skipped,
            action_taken: "gpio".to_string(),
            data: serde_json::json!({}),
            summary: "GPIO configuration not yet implemented".to_string(),
            details: None,
            state_delta: super::session_state::StateDelta::none(),
            suggested_actions: vec![],
            error: None,
        })
    }

    async fn show_config(&self, _config: &ESP32Config, args: &HashMap<String, Value>) -> Result<ToolOutput, String> {
        let project_path = args.get("project_path")
            .and_then(|v| v.as_str())
            .map(|s| std::path::PathBuf::from(s))
            .unwrap_or_else(|| std::path::PathBuf::from("."));

        // Only check sdkconfig.defaults (never read autogenerated sdkconfig - too large)
        let defaults_path = project_path.join("sdkconfig.defaults");
        
        let mut has_config = false;
        let mut config_info = serde_json::json!({});
        
        if defaults_path.exists() {
            let content = tokio::fs::read_to_string(&defaults_path).await
                .map_err(|e| format!("Failed to read sdkconfig.defaults: {}", e))?;
            config_info["defaults_lines"] = serde_json::json!(content.lines().count());
            has_config = true;
        }
        
        if !has_config {
            return Ok(ToolOutput {
                status: super::output_protocol::ToolStatus::PartialSuccess,
                action_taken: "show".to_string(),
                data: serde_json::json!({}),
                summary: "No sdkconfig.defaults found - run 'idf.py reconfigure' first or use 'sdkconfig' operation to create it".to_string(),
                details: Some("Note: This tool only reads sdkconfig.defaults (user-editable), not the autogenerated sdkconfig file.".to_string()),
                state_delta: super::session_state::StateDelta::none(),
                suggested_actions: vec![],
                error: None,
            });
        }

        Ok(ToolOutput::success(
            format!("Configuration from {}", project_path.display()),
            config_info,
        ))
    }

    /// Get device information (chip type, revision, flash size, etc.)
    async fn get_device_info(&self, config: &ESP32Config, port: &str) -> Result<serde_json::Value, String> {
        // Get chip info using IdfCommand::esptool
        let chip_result = IdfCommand::esptool("chip-id")
            .args(&["--port", port])
            .timeout_secs(30)
            .no_parse_errors()
            .execute(config).await?;

        if !chip_result.success {
            return Err(format!("Failed to get chip info: {}", chip_result.stderr));
        }

        let stdout = &chip_result.stdout;
        
        // Parse structured info from chip-id output
        let mut chip_type = None;
        let mut revision = None;
        let mut features = None;
        let mut crystal_freq = None;
        let mut mac = None;

        for line in stdout.lines() {
            if line.contains("Chip is") || line.starts_with("Chip type:") {
                if line.contains("Chip is") {
                    if let Some(start) = line.find("Chip is") {
                        let rest = &line[start + "Chip is".len()..].trim();
                        if let Some(rev_pos) = rest.find("(revision") {
                            chip_type = Some(rest[..rev_pos].trim().to_string());
                            let rev_part = &rest[rev_pos..];
                            if let Some(v_start) = rev_part.find('v') {
                                if let Some(end) = rev_part[v_start..].find(')') {
                                    revision = rev_part.get(v_start..v_start+end).map(|s| s.to_string());
                                }
                            }
                        } else {
                            chip_type = Some(rest.to_string());
                        }
                    }
                } else if line.starts_with("Chip type:") {
                    if let Some(colon_pos) = line.find(':') {
                        let rest = &line[colon_pos + 1..].trim();
                        if let Some(rev_pos) = rest.find("(revision") {
                            chip_type = Some(rest[..rev_pos].trim().to_string());
                            let rev_part = &rest[rev_pos..];
                            if let Some(v_start) = rev_part.find('v') {
                                if let Some(end) = rev_part[v_start..].find(')') {
                                    revision = rev_part.get(v_start..v_start+end).map(|s| s.to_string());
                                }
                            }
                        } else {
                            chip_type = Some(rest.to_string());
                        }
                    }
                }
            } else if line.starts_with("Features:") {
                if let Some(colon_pos) = line.find(':') {
                    features = Some(line[colon_pos + 1..].trim().to_string());
                }
            } else if line.contains("Crystal is") || line.starts_with("Crystal frequency:") {
                if line.contains("Crystal is") {
                    if let Some(start) = line.find("Crystal is") {
                        crystal_freq = Some(line[start + "Crystal is".len()..].trim().to_string());
                    }
                } else if line.starts_with("Crystal frequency:") {
                    if let Some(colon_pos) = line.find(':') {
                        crystal_freq = Some(line[colon_pos + 1..].trim().to_string());
                    }
                }
            } else if line.starts_with("MAC:") && mac.is_none() {
                if let Some(colon_pos) = line.find(':') {
                    let mac_str = line[colon_pos + 1..].trim();
                    if mac_str.len() >= 17 {
                        mac = Some(mac_str.to_string());
                    }
                }
            }
        }

        // Try to get flash ID and size
        let mut flash_id = None;
        let mut flash_manufacturer = None;
        let mut flash_device = None;
        let mut flash_size = None;
        
        if let Ok(flash_result) = IdfCommand::esptool("flash-id")
            .args(&["--port", port])
            .timeout_secs(30)
            .no_parse_errors()
            .execute(config).await
        {
            if flash_result.success {
                for line in flash_result.stdout.lines() {
                    if line.contains("Flash ID:") {
                        if let Some(colon_pos) = line.find(':') {
                            flash_id = Some(line[colon_pos + 1..].trim().to_string());
                        }
                    } else if line.starts_with("Manufacturer:") {
                        if let Some(colon_pos) = line.find(':') {
                            flash_manufacturer = Some(line[colon_pos + 1..].trim().to_string());
                        }
                    } else if line.starts_with("Device:") {
                        if let Some(colon_pos) = line.find(':') {
                            flash_device = Some(line[colon_pos + 1..].trim().to_string());
                        }
                    } else if line.contains("Detected flash size:") {
                        if let Some(start) = line.find("Detected flash size:") {
                            flash_size = Some(line[start + "Detected flash size:".len()..].trim().to_string());
                        }
                    }
                }
            }
        }

        Ok(serde_json::json!({
            "port": port,
            "chip_type": chip_type,
            "revision": revision,
            "features": features,
            "crystal_frequency": crystal_freq,
            "mac_address": mac,
            "flash_id": flash_id,
            "flash_manufacturer": flash_manufacturer,
            "flash_device": flash_device,
            "flash_size": flash_size,
        }))
    }

    /// Auto-configure sdkconfig.defaults based on connected device
    async fn auto_configure_from_device(&self, config: &ESP32Config, args: &HashMap<String, Value>) -> Result<ToolOutput, String> {
        let project_path = args.get("project_path")
            .and_then(|v| v.as_str())
            .map(|s| std::path::PathBuf::from(s))
            .unwrap_or_else(|| std::path::PathBuf::from("."));

        let port = resolve_device_port(config, args, PortResolutionPolicy::PreferKnown).await?;

        // Step 1: Get device info
        let device_info = self.get_device_info(config, &port).await?;
        
        let chip_type = device_info.get("chip_type")
            .and_then(|v| v.as_str())
            .ok_or("Could not detect chip type from device")?;
        
        // Map chip type to IDF target
        let target = match chip_type {
            "ESP32-P4" => "esp32p4",
            "ESP32-S3" => "esp32s3",
            "ESP32-C3" => "esp32c3",
            "ESP32-C6" => "esp32c6",
            "ESP32-S2" => "esp32s2",
            "ESP32" => "esp32",
            _ => return Err(format!("Unsupported chip type: {}", chip_type)),
        };
        
        let revision = device_info.get("revision")
            .and_then(|v| v.as_str());
        
        let flash_size = device_info.get("flash_size")
            .and_then(|v| v.as_str());

        // Step 2: Set target first (before generating defaults)
        // This ensures sdkconfig is generated for the correct target
        let set_target_result = IdfCommand::new("set-target")
            .arg(target)
            .project_path(&project_path)
            .timeout_secs(120)
            .execute(config).await?;
        
        if !set_target_result.success {
            return Err(format!("Failed to set target '{}': {}", target, set_target_result.stderr));
        }
        
        let mut changes_made = vec![format!("Set target to {}", target)];

        // Step 3: Generate appropriate defaults
        let mut defaults = Vec::new();
        
        // Handle chip revision (ECO1 vs ECO3 for ESP32-P4)
        if let Some(rev) = revision {
            if chip_type.contains("ESP32-P4") {
                // Parse revision: "v1.0" -> ECO1, "v3.0" -> ECO3
                if rev.starts_with("v1.") {
                    defaults.push("CONFIG_ESP32P4_SELECTS_REV_LESS_V3=y".to_string());
                    changes_made.push("Set revision to ECO1 (v1.x)".to_string());
                    
                    // ECO1 needs conservative settings
                    defaults.push("CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ=360".to_string());
                    defaults.push("CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_360=y".to_string());
                    defaults.push("CONFIG_BOOTLOADER_CPU_CLK_FREQ_MHZ=100".to_string());
                    defaults.push("CONFIG_ESPTOOLPY_FLASHFREQ_40M=y".to_string());
                    changes_made.push("Set conservative clock settings for ECO1 (CPU 360MHz, bootloader 100MHz, flash 40MHz)".to_string());
                } else if rev.starts_with("v3.") {
                    // ECO3 can use higher settings
                    defaults.push("CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ=400".to_string());
                    defaults.push("CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_400=y".to_string());
                    defaults.push("CONFIG_BOOTLOADER_CPU_CLK_FREQ_MHZ=100".to_string());
                    defaults.push("CONFIG_ESPTOOLPY_FLASHFREQ_80M=y".to_string());
                    changes_made.push("Set standard clock settings for ECO3 (CPU 400MHz, bootloader 100MHz, flash 80MHz)".to_string());
                }
            }
        }

        // Handle flash size
        if let Some(size) = flash_size {
            // Convert "16MB" -> "CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y"
            // Remove spaces and convert to config format
            let size_clean = size.replace(" ", "").to_uppercase();
            defaults.push(format!("CONFIG_ESPTOOLPY_FLASHSIZE_{}=y", size_clean));
            changes_made.push(format!("Set flash size to {}", size));
        }

        if defaults.is_empty() {
            return Ok(ToolOutput {
                status: super::output_protocol::ToolStatus::PartialSuccess,
                action_taken: "auto_configure".to_string(),
                data: serde_json::json!({
                    "chip_type": chip_type,
                    "revision": revision,
                    "flash_size": flash_size,
                }),
                summary: format!("Detected {} {} (flash: {}) but no configuration changes needed", 
                    chip_type,
                    revision.unwrap_or("unknown revision"),
                    flash_size.unwrap_or("unknown size")),
                details: Some("Device detected but no auto-configuration rules apply to this chip/revision combination.".to_string()),
                state_delta: super::session_state::StateDelta::none(),
                suggested_actions: vec![],
                error: None,
            });
        }

        // Step 4: Read existing sdkconfig.defaults
        let defaults_path = project_path.join("sdkconfig.defaults");
        let existing_content = if defaults_path.exists() {
            tokio::fs::read_to_string(&defaults_path).await
                .unwrap_or_default()
        } else {
            String::new()
        };

        // Step 5: Merge with existing (avoid duplicates)
        let mut lines: Vec<String> = existing_content.lines()
            .map(|s| s.to_string())
            .collect();
        
        // Remove comment lines that start with our auto-generated header
        lines.retain(|line| !line.starts_with("# Auto-generated from detected device:"));
        
        for new_line in &defaults {
            let key = new_line.split('=').next().unwrap_or("");
            // Remove existing line with same key
            lines.retain(|line| !line.starts_with(&format!("{}=", key)));
            // Add new line
            lines.push(new_line.clone());
        }

        // Step 6: Add header comment
        let header = format!(
            "# Auto-generated from detected device: {} {} (flash: {})\n",
            chip_type,
            revision.unwrap_or("unknown"),
            flash_size.unwrap_or("unknown")
        );
        
        let content = format!("{}{}", header, lines.join("\n"));
        tokio::fs::write(&defaults_path, content).await
            .map_err(|e| format!("Failed to write sdkconfig.defaults: {}", e))?;

        // Step 7: Optionally reconfigure
        let reconfigure = args.get("reconfigure")
            .and_then(|v| v.as_bool())
            .unwrap_or(true);

        let reconfigure_msg = if reconfigure {
            let result = IdfCommand::reconfigure_fresh(config, &project_path, 60).await?;
            
            if !result.success {
                return Err(format!("Reconfigure failed: {}", result.stderr));
            }
            " (reconfigured)"
        } else {
            " (run 'idf.py reconfigure' to apply)"
        };

        Ok(ToolOutput::success(
            format!("Auto-configured sdkconfig.defaults for {} {} (flash: {}){}", 
                chip_type, 
                revision.unwrap_or("unknown"),
                flash_size.unwrap_or("unknown"),
                reconfigure_msg),
            serde_json::json!({
                "chip_type": chip_type,
                "revision": revision,
                "flash_size": flash_size,
                "defaults_added": defaults.len(),
                "changes": changes_made,
                "reconfigured": reconfigure,
            }),
        ))
    }

    /// Apply a board preset configuration
    async fn apply_preset(&self, config: &ESP32Config, args: &HashMap<String, Value>) -> Result<ToolOutput, String> {
        let project_path = args.get("project_path")
            .and_then(|v| v.as_str())
            .map(|s| std::path::PathBuf::from(s))
            .unwrap_or_else(|| std::path::PathBuf::from("."));

        let preset_name = args.get("preset_name")
            .and_then(|v| v.as_str())
            .ok_or("Missing required parameter: preset_name")?;

        // Agentic: Use board_id from session state if not provided in args
        let board_id_from_args = args.get("board_id").and_then(|v| v.as_str());
        
        // Get board_id from session if not in args (async)
        let board_id = if let Some(bid) = board_id_from_args {
            Some(bid.to_string())
        } else {
            let state = get_state().await;
            state.session.board_id.clone()
        };
        
        let board_id = board_id.as_deref();

        // If board_id available (from args or session), use schema-based preset application
        if let Some(board_id) = board_id {
            let result = self.apply_schema_preset(config, board_id, preset_name, &project_path, args).await?;
            
            // Agentic: Auto-verify device after applying preset (if device is connected)
            let active_device_port = {
                let state = get_state().await;
                state.session.active_device.as_ref().map(|d| d.port.clone())
            };
            
            if let Some(port) = active_device_port {
                // Attempt auto-verification (non-blocking)
                use super::esp32_device::ESP32Device;
                let device_tool = ESP32Device { config_path: String::new() };
                let verify_args = serde_json::json!({
                    "board_id": board_id,
                    "port": port,
                });
                if let Ok(verify_output) = device_tool.verify_device(config, &serde_json::from_value(verify_args).unwrap_or_default()).await {
                    match verify_output.status {
                        super::output_protocol::ToolStatus::Success => {
                            let mut state = get_state_mut().await;
                            state.session.mark_board_verified();
                            drop(state);
                        }
                        _ => {} // PartialSuccess or other - don't mark as verified
                    }
                }
            }
            
            return Ok(result);
        }

        let reconfigure = args.get("reconfigure")
            .and_then(|v| v.as_bool())
            .unwrap_or(true);

        match preset_name {
            "wifi_remote_func_ev" => self.apply_wifi_remote_func_ev_preset(config, &project_path, reconfigure).await,
            _ => Err(format!("Unknown preset: {}. Supported presets: wifi_remote_func_ev", preset_name)),
        }
    }

    /// Apply preset from board definition schema
    async fn apply_schema_preset(
        &self,
        config: &ESP32Config,
        board_id: &str,
        preset_name: &str,
        project_path: &std::path::PathBuf,
        args: &HashMap<String, Value>,
    ) -> Result<ToolOutput, String> {
        // Fetch board definition
        let board_def = self.fetch_board_definition(config, board_id).await?;

        // Resolve preset (with inheritance)
        let mut sdkconfig_values = std::collections::HashMap::new();
        let preset = board_def.config_presets.get(preset_name).ok_or_else(|| {
            let available = board_def.config_presets.keys().cloned().collect::<Vec<_>>().join(", ");
            format!("Preset '{}' not found for board {}. Available: {}", preset_name, board_id, available)
        })?;

        if let Some(extends) = &preset.extends {
            if let Some(base) = board_def.config_presets.get(extends) {
                sdkconfig_values.extend(base.sdkconfig.clone());
            } else {
                return Err(format!("Base preset '{}' not found for board {}", extends, board_id));
            }
        }
        sdkconfig_values.extend(preset.sdkconfig.clone());

        // Apply sdkconfig values to sdkconfig.defaults
        self.apply_sdkconfig_values(project_path, sdkconfig_values.clone()).await?;

        // Optional reconfigure (default true)
        let reconfigure = args.get("reconfigure")
            .and_then(|v| v.as_bool())
            .unwrap_or(true);

        if reconfigure {
            let result = IdfCommand::reconfigure_fresh(config, project_path, 60).await?;
            if !result.success {
                return Err(format!("Reconfigure failed: {}", result.stderr));
            }
        }

        Ok(ToolOutput::success(
            format!("Applied preset '{}' for board {}", preset_name, board_id),
            serde_json::json!({
                "board_id": board_id,
                "preset": preset_name,
                "configs_applied": sdkconfig_values.len(),
                "reconfigured": reconfigure,
            }),
        ))
    }

    async fn fetch_board_definition(
        &self,
        _config: &ESP32Config,
        board_id: &str,
    ) -> Result<BoardDefinition, String> {
        let state = get_state().await;
        let cache = &state.cache;

        let board_url = board_definition_url(board_id);

        cache.get_board_definition(board_id, async {
            let client = reqwest::Client::builder()
                .connect_timeout(std::time::Duration::from_secs(5))
                .timeout(std::time::Duration::from_secs(15))
                .build()
                .map_err(|e| format!("Failed to build HTTP client: {}", e))?;
            let response = client.get(&board_url)
                .send()
                .await
                .map_err(|e| format!("Failed to fetch board definition: {}", e))?;

            if !response.status().is_success() {
                return Err(format!("Server returned error: {}", response.status()));
            }

            let board_def: BoardDefinition = response.json()
                .await
                .map_err(|e| format!("Failed to parse board definition: {}", e))?;
            Ok(board_def)
        }).await
    }

    async fn apply_sdkconfig_values(
        &self,
        project_path: &std::path::PathBuf,
        values: std::collections::HashMap<String, String>,
    ) -> Result<(), String> {
        let updates: Vec<(String, String)> = values.into_iter().collect();
        Self::update_sdkconfig_defaults(project_path, &updates).await?;
        Ok(())
    }

    /// Apply ESP32-P4 Function-EV board Wi-Fi Remote preset
    async fn apply_wifi_remote_func_ev_preset(
        &self,
        config: &ESP32Config,
        project_path: &std::path::PathBuf,
        reconfigure: bool,
    ) -> Result<ToolOutput, String> {
        // Check if target is set to esp32p4 (from sdkconfig.defaults, not autogenerated sdkconfig)
        let defaults_path = project_path.join("sdkconfig.defaults");
        let is_p4 = if defaults_path.exists() {
            if let Ok(content) = tokio::fs::read_to_string(&defaults_path).await {
                content.contains("CONFIG_IDF_TARGET=\"esp32p4\"")
            } else {
                false
            }
        } else {
            false
        };

        if !is_p4 {
            // Try to set target first
            let set_target_result = IdfCommand::new("set-target")
                .arg("esp32p4")
                .project_path(project_path)
                .timeout_secs(120)
                .execute(config).await?;
            
            if !set_target_result.success {
                return Err(format!("Failed to set target to esp32p4. Please run 'idf.py set-target esp32p4' first: {}", set_target_result.stderr));
            }
        }

        // Check for and remove esp-extconn from idf_component.yml if present
        let main_component_yml = project_path.join("main").join("idf_component.yml");
        let root_component_yml = project_path.join("idf_component.yml");
        let mut removed_extconn = false;
        let mut extconn_warning = None;

        for component_yml in &[&main_component_yml, &root_component_yml] {
            if component_yml.exists() {
                if let Ok(content) = tokio::fs::read_to_string(component_yml).await {
                    if content.contains("esp-extconn") {
                        // Parse YAML and remove esp-extconn
                        match serde_yaml::from_str::<serde_yaml::Value>(&content) {
                            Ok(mut yaml) => {
                                if let Some(deps) = yaml.get_mut("dependencies") {
                                    if let Some(deps_map) = deps.as_mapping_mut() {
                                        deps_map.remove("esp-extconn");
                                        match serde_yaml::to_string(&yaml) {
                                            Ok(updated) => {
                                                if let Err(e) = tokio::fs::write(component_yml, updated).await {
                                                    extconn_warning = Some(format!("Found esp-extconn in {:?} but failed to remove it: {}", component_yml, e));
                                                } else {
                                                    removed_extconn = true;
                                                }
                                            }
                                            Err(e) => {
                                                extconn_warning = Some(format!("Found esp-extconn in {:?} but failed to serialize YAML: {}", component_yml, e));
                                            }
                                        }
                                    }
                                }
                            }
                            Err(e) => {
                                extconn_warning = Some(format!("Found esp-extconn in {:?} but failed to parse YAML: {}", component_yml, e));
                            }
                        }
                    }
                }
            }
        }

        // Determine which defaults file to use (sdkconfig.defaults.esp32p4 if exists, else sdkconfig.defaults)
        let defaults_path = project_path.join("sdkconfig.defaults.esp32p4");
        let defaults_path_fallback = project_path.join("sdkconfig.defaults");
        let defaults_path = if defaults_path.exists() {
            defaults_path
        } else {
            defaults_path_fallback
        };

        // Read existing defaults
        let existing_content = if defaults_path.exists() {
            tokio::fs::read_to_string(&defaults_path).await
                .map_err(|e| format!("Failed to read {:?}: {}", defaults_path, e))?
        } else {
            String::new()
        };

        // Function-EV Wi-Fi Remote defaults
        let func_ev_defaults = vec![
            "CONFIG_SLAVE_IDF_TARGET_ESP32C6=y",
            "CONFIG_ESP_HOSTED_P4_DEV_BOARD_FUNC_BOARD=y",
            "CONFIG_WIFI_RMT_STATIC_RX_BUFFER_NUM=16",
            "CONFIG_WIFI_RMT_DYNAMIC_RX_BUFFER_NUM=64",
            "CONFIG_WIFI_RMT_DYNAMIC_TX_BUFFER_NUM=64",
            "CONFIG_WIFI_RMT_AMPDU_TX_ENABLED=y",
            "CONFIG_WIFI_RMT_TX_BA_WIN=32",
            "CONFIG_WIFI_RMT_AMPDU_RX_ENABLED=y",
            "CONFIG_WIFI_RMT_RX_BA_WIN=32",
            "CONFIG_LWIP_TCP_SND_BUF_DEFAULT=65534",
            "CONFIG_LWIP_TCP_WND_DEFAULT=65534",
            "CONFIG_LWIP_TCP_RECVMBOX_SIZE=64",
            "CONFIG_LWIP_UDP_RECVMBOX_SIZE=64",
            "CONFIG_LWIP_TCPIP_RECVMBOX_SIZE=64",
            "CONFIG_LWIP_TCP_SACK_OUT=y",
        ];

        // Merge with existing (remove duplicates, keep order)
        let mut lines: Vec<String> = existing_content.lines()
            .map(|s| s.to_string())
            .collect();

        // Remove comment lines that start with our preset header
        lines.retain(|line| !line.starts_with("# ESP32-P4 Function-EV Wi-Fi Remote preset"));

        // Remove existing lines that match our defaults
        for default_line in &func_ev_defaults {
            let key = default_line.split('=').next().unwrap_or("");
            lines.retain(|line| !line.starts_with(&format!("{}=", key)));
        }

        // Add preset header and defaults
        lines.push("# ESP32-P4 Function-EV Wi-Fi Remote preset".to_string());
        lines.push("# Applied by esp32_config preset operation".to_string());
        lines.push("".to_string());
        for default_line in &func_ev_defaults {
            lines.push(default_line.to_string());
        }

        // Write back
        let content = lines.join("\n");
        tokio::fs::write(&defaults_path, content).await
            .map_err(|e| format!("Failed to write {:?}: {}", defaults_path, e))?;

        // Optionally reconfigure
        let reconfigure_msg = if reconfigure {
            let result = IdfCommand::reconfigure_fresh(config, project_path, 60).await?;
            
            if !result.success {
                return Err(format!("Reconfigure failed: {}", result.stderr));
            }
            " (reconfigured)"
        } else {
            " (run 'idf.py reconfigure' to apply)"
        };

        let mut changes = vec![
            format!("Applied Function-EV Wi-Fi Remote defaults to {:?}", defaults_path.file_name().unwrap_or_default()),
        ];
        if removed_extconn {
            changes.push("Removed esp-extconn from idf_component.yml (conflicts with esp_hosted)".to_string());
        }
        if let Some(ref warning) = extconn_warning {
            changes.push(format!("Warning: {}", warning));
        }

        let mut output = ToolOutput::success(
            format!("Applied wifi_remote_func_ev preset{}", reconfigure_msg),
            serde_json::json!({
                "preset": "wifi_remote_func_ev",
                "defaults_file": defaults_path.file_name().and_then(|n| n.to_str()).unwrap_or("sdkconfig.defaults"),
                "defaults_added": func_ev_defaults.len(),
                "removed_esp_extconn": removed_extconn,
                "reconfigured": reconfigure,
                "changes": changes,
            }),
        );

        if extconn_warning.is_some() {
            output.details = extconn_warning;
        }

        Ok(output)
    }
}

